In [7]:
for i in [1,2,3,4,5]:
    for j in [1,2,3,4,5]:
        print i+j
print "done looping"

2
3
4
5
6
3
4
5
6
7
4
5
6
7
8
5
6
7
8
9
6
7
8
9
10
done looping


In [8]:
list_of_lists = [[1,2,3],
                 [4,5,6],
                 [7,8,9]]
# looks better this way rather than writing the entire in one line

In [9]:
import re
my_regex = re.compile("[0-9]+",re.I)

In [10]:
#importing lesson

import matplotlib.pyplot as plt

from collections import defaultdict, Counter
lookup = defaultdict(int)
my_counter =Counter()

In [11]:
def apply_to_one(f):
    return f(1)

In [12]:
y = apply_to_one(lambda x: x + 4)  #using lambda architecture

y

5

In [13]:
try:
    print 0/0

except ZeroDivisionError:
    print "cannot divide by zero"

cannot divide by zero


In [14]:
print 1 in [1,2,3]
print 0 in [1,2,3]

True
False


In [15]:
x = [1,2,3]
x.extend([4,5,6])
x

[1, 2, 3, 4, 5, 6]

In [16]:
grades = {"Joel":80, "Tim":95}

In [17]:
grades["Tim"]

95

In [18]:
print "Joel" in grades
print "Kate" in grades

True
False


In [19]:
grades.get("Joel", 0)

80

In [20]:
grades.get("Joel")

80

In [21]:
grades.get("No one")

In [22]:
grades["Tim"] = 99
grades["Kate"] = 100
len(grades)

3

In [23]:
tweet = {
"user" : "joelgrus",
"text" : "Data Science is Awesome",
"retweet_count" : 100,
"hashtags" : ["#data", "#science", "#datascience", "#awesome", "#yolo"]
}

tweet_keys = tweet.keys()
tweet_values = tweet.values()
tweet_items = tweet.items()

In [24]:
print tweet_keys

['text', 'retweet_count', 'hashtags', 'user']


In [25]:
print tweet_values

['Data Science is Awesome', 100, ['#data', '#science', '#datascience', '#awesome', '#yolo'], 'joelgrus']


In [26]:
print tweet_items

[('text', 'Data Science is Awesome'), ('retweet_count', 100), ('hashtags', ['#data', '#science', '#datascience', '#awesome', '#yolo']), ('user', 'joelgrus')]


In [27]:
"user" in tweet

True

In [28]:
document = ["key" , "key" , "key"]
# word counting in a dictionary
word_counts = {}

for word in document:
    if word in word_counts:
        word_counts[word] +=1
    else:
        word_counts[word] = 1

In [29]:
document = ["key" , "key" , "key"]

word_counts = {}

for word in document:
    try:
        word_counts[word] +=1
    except KeyError:
        word_counts[word] = 1

In [30]:
# third way of counting from the book, pretty interesting

document = ["key" , "key" , "key","value","value"]

word_counts = {}

for word in document:
    previous_count = word_counts.get(word, 0)
    word_counts[word] = previous_count + 1

In [31]:
word_counts

{'key': 3, 'value': 2}

In [32]:
from collections import defaultdict

word_counts = defaultdict(int)
for word in document:
    word_counts[word] += 1

In [33]:
word_counts

defaultdict(<type 'int'>, {'value': 2, 'key': 3})

In [34]:
s = set()
s.add(1)
s.add(2)
s.add(2)
x = len(s)
y = 2 in s
z = 3 in s

In [35]:
print y 
print z

True
False


In [36]:
# ternary, one liners

parity = "even" if x % 2 == 0 else "odd"

In [37]:
def parity(x):
    if x % 2 == 0:
        print "even"
    else:
        print "odd"

In [38]:
parity(3)

odd


In [39]:
parity(6)

even


In [40]:
for x in range(10):
    if x == 3:
        continue
    if x == 5:
        break
    print x    

0
1
2
4


In [41]:
x = [4,1,2,3]

y = sorted(x)

x.sort()

In [42]:
x

[1, 2, 3, 4]

In [43]:
1 in x

True

In [44]:
even_numbers = [x for x in range(5) if x % 2 == 0]

In [45]:
even_numbers

[0, 2, 4]

In [46]:
squares = [x**2 for x in range(5)]

In [47]:
squares

[0, 1, 4, 9, 16]

In [48]:
even_squares = [x**2 for x in range(5) if x%2 ==0]

In [49]:
even_squares # using both even and squares together

[0, 4, 16]

In [50]:
odd_squares = [ x**2 for x in range(5) if x % 3 ==0]

In [51]:
odd_squares

[0, 9]

In [52]:
square_dict = {x : x for x in range(5)}

In [53]:
square_dict

{0: 0, 1: 1, 2: 2, 3: 3, 4: 4}

In [54]:
#multiple pairs

pairs = [(x,y) for x in range(5) for y in range(5)]

In [55]:
pairs 

[(0, 0),
 (0, 1),
 (0, 2),
 (0, 3),
 (0, 4),
 (1, 0),
 (1, 1),
 (1, 2),
 (1, 3),
 (1, 4),
 (2, 0),
 (2, 1),
 (2, 2),
 (2, 3),
 (2, 4),
 (3, 0),
 (3, 1),
 (3, 2),
 (3, 3),
 (3, 4),
 (4, 0),
 (4, 1),
 (4, 2),
 (4, 3),
 (4, 4)]

In [56]:
increasing_pairs = [(x,y) for x in range(10) for y in range(x+1,10)]

In [57]:
increasing_pairs

[(0, 1),
 (0, 2),
 (0, 3),
 (0, 4),
 (0, 5),
 (0, 6),
 (0, 7),
 (0, 8),
 (0, 9),
 (1, 2),
 (1, 3),
 (1, 4),
 (1, 5),
 (1, 6),
 (1, 7),
 (1, 8),
 (1, 9),
 (2, 3),
 (2, 4),
 (2, 5),
 (2, 6),
 (2, 7),
 (2, 8),
 (2, 9),
 (3, 4),
 (3, 5),
 (3, 6),
 (3, 7),
 (3, 8),
 (3, 9),
 (4, 5),
 (4, 6),
 (4, 7),
 (4, 8),
 (4, 9),
 (5, 6),
 (5, 7),
 (5, 8),
 (5, 9),
 (6, 7),
 (6, 8),
 (6, 9),
 (7, 8),
 (7, 9),
 (8, 9)]

In [58]:
def lazy_range(n):
    
    while n>0:
        print n
        n=n-1
    print "Blast off Homie!"
        

In [59]:
lazy_range(5)

5
4
3
2
1
Blast off Homie!


In [60]:
import time

print time.localtime()

time.struct_time(tm_year=2016, tm_mon=1, tm_mday=28, tm_hour=15, tm_min=56, tm_sec=16, tm_wday=3, tm_yday=28, tm_isdst=0)


http://www.tutorialspoint.com/python/python_date_time.html
https://docs.python.org/2/library/timeit.html

In [61]:
import timeit 

In [62]:
[i for i in range(5)]

[0, 1, 2, 3, 4]

In [63]:
def test():
    return [i for i in range(100)]

In [64]:
if __name__ == "__main__":
    import timeit
    setup = "from __main__ import test"
    print timeit.timeit("test()", setup=setup)

7.05664896965


In [65]:
#randomness

import random

In [66]:
four_randoms = [random.random() for _ in range(4)]

In [67]:
four_randoms

[0.3638910904759627,
 0.4505058438228605,
 0.5152915637317763,
 0.8412916722930929]

In [68]:
random_integer =[ random.randint(1,5)]

In [69]:
random_integer

[2]

In [70]:
random.randrange(10)

1

In [71]:
random.randrange(5,10)

9

In [72]:
ten = range(10)
random.shuffle(ten)

In [73]:
print ten

[5, 3, 6, 4, 8, 9, 2, 1, 7, 0]


In [74]:
random_choice = random.choice(["Amy","Jared","Mike","Nir","Brian"])

In [75]:
random_choice

'Mike'

In [76]:
lottery_numbers = range(60)

In [77]:
winning_numbers = random.sample(lottery_numbers, 5)

In [78]:
winning_numbers

[43, 38, 21, 0, 48]

In [79]:
#Enumerate

idk = [1,2,3,4,5]

for i, j in enumerate(idk):
    print " %s %d , %s %d" % ("Index:", i , "Item:", j)

 Index: 0 , Item: 1
 Index: 1 , Item: 2
 Index: 2 , Item: 3
 Index: 3 , Item: 4
 Index: 4 , Item: 5


In [80]:
list1 = ['a','b','c']
list2 = [1,2,3]
zip(list1,list2)

[('a', 1), ('b', 2), ('c', 3)]

In [81]:
# unzip

pairs = [('a', 1), ('b', 2), ('c', 3)]

letters, numbers = zip(*pairs)

In [82]:
letters

('a', 'b', 'c')

In [83]:
numbers

(1, 2, 3)

In [84]:
def add(a,b): return a + b
add(*[1,2])

3

#more seaborn
http://stanford.edu/~mwaskom/software/seaborn-dev/tutorial.html

In [85]:
import numpy as np
# creating identity matrix

def identity_matrix(n): # n is the maxtrix size, can only be sqaure
    matrix = np.zeros((n,n))
    for i in range(n):
        matrix[i][i] = 1
    return matrix


In [86]:
identity_matrix(5)

array([[ 1.,  0.,  0.,  0.,  0.],
       [ 0.,  1.,  0.,  0.,  0.],
       [ 0.,  0.,  1.,  0.,  0.],
       [ 0.,  0.,  0.,  1.,  0.],
       [ 0.,  0.,  0.,  0.,  1.]])

In [87]:
A = [[1, 2, 3], # A has 2 rows and 3 columns
    [4, 5, 6]]

B = [[1, 2], # B has 3 rows and 2 columns
    [3, 4],
    [5, 6]]

In [88]:
def shape(A):
    num_rows = len(A)
    num_cols = len(A[0]) if A else 0
    return num_rows , num_cols

In [89]:
print shape(A)

print np.shape(A)

(2, 3)
(2, 3)


In [90]:
friendships = [(0, 1), (0, 2), (1, 2), (1, 3), (2, 3), (3, 4),
(4, 5), (5, 6), (5, 7), (6, 8), (7, 8), (8, 9)]

In [91]:
def tuple_to_matrix(s):
    singles = []
    for i in friendships:
        singles.append(i[0])
        singles.append(i[1])
    
    n = max(singles) + 1
    matrix = np.zeros((n,n))
    
    for i in friendships:
        matrix[i[0]][i[1]] = 1
        matrix[i[1]][i[0]] = 1 
    
    return matrix

In [92]:
tuple_to_matrix(friendships)

array([[ 0.,  1.,  1.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 1.,  0.,  1.,  1.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 1.,  1.,  0.,  1.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  1.,  1.,  0.,  1.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  1.,  0.,  1.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  1.,  0.,  1.,  1.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  1.,  0.,  0.,  1.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  1.,  0.,  0.,  1.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  1.,  1.,  0.,  1.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  1.,  0.]])

In [93]:
#                # user 0 1 2 3 4 5 6 7 8 9
# friendships = [[0, 1, 1, 0, 0, 0, 0, 0, 0, 0], # user 0
#                 [1, 0, 1, 1, 0, 0, 0, 0, 0, 0], # user 1
#                 [1, 1, 0, 1, 0, 0, 0, 0, 0, 0], # user 2
#                 [0, 1, 1, 0, 1, 0, 0, 0, 0, 0], # user 3
#                 [0, 0, 0, 1, 0, 1, 0, 0, 0, 0], # user 4
#                 [0, 0, 0, 0, 1, 0, 1, 1, 0, 0], # user 5
#                 [0, 0, 0, 0, 0, 1, 0, 0, 1, 0], # user 6
#                 [0, 0, 0, 0, 0, 1, 0, 0, 1, 0], # user 7
#                 [0, 0, 0, 0, 0, 0, 1, 1, 0, 1], # user 8
#                 [0, 0, 0, 0, 0, 0, 0, 0, 1, 0]] # user 9

In [94]:
def mode(x):
    mode = Counter(x)
    return mode.most_common()[0][0]

In [95]:
x = Counter([1,1,1,2,2,3,4,5,6,0,0,0,0,0])

In [96]:
from __future__ import division
def median(x):
    midpoint = len(x)//2
    if len(x) % 2 == 1:
        median = x[midpoint]
    else:
        median = (x[midpoint] + x[midpoint-1])/2 
    return median    

In [97]:
print median([1,2,3,4,5,6,7,8,9])

5


In [98]:
print median([1,2,3,4,5,6,7,8,9,10])

5.5


In [99]:
np.median([1,2,3,4,5,6,7,8,9,10])

5.5

In [100]:
def mean(x): 
    return sum(x) / len(x)

def variance(x):
    total = 0
    for i in x:
        total += (i-mean(x))**2 
    return total/ len(x) 

def std(x):
    return (variance(x))**.5

In [101]:
n = [1,2,3,4,5,6,7,8,9,10]

In [102]:
print mean(n)
print variance(n)
print std(n)

5.5
8.25
2.87228132327


In [103]:
print np.mean(n)
print np.var(n)
print np.std(n)

5.5
8.25
2.87228132327


In [104]:
def upper(x):
    q3 = (len(n)*.75)
    return q3

In [105]:
upper(n)

7.5

In [106]:
def lower(x):
    q1 = (len(n)*.25)
    return q1

In [107]:
lower(n)

2.5

In [108]:
def interquartile(x):
    return upper(x)-lower(x)

In [109]:
interquartile(n)

5.0

In [122]:
def covariance(x,y):
    xy_sum = 0
    y_mean= sum(y)/float(len(y))
    x_mean= sum(x)/float(len(x))
    n = len(x)
    for i in range(n):
        xy_sum += (x[i]- x_mean)*(y[i]-y_mean)

    return  xy_sum / (n-1)

In [123]:
def correlation(x,y):
    stdev_x = std(x)
    stdev_y = std(y)
    if stdev_x > 0 and stdev_y > 0:
        return covariance(x,y)/stdev_x/stdev_y
    else:
        return 0

In [124]:
a = [1,2,3,4,5,6,7,8,9,10,11,12]

b = [2,3,4,5,6,7,8,15,10,11,3,2]

In [125]:
covariance(a,b)

4.636363636363638

In [126]:
np.cov(a,b)

array([[ 13.        ,   4.63636364],
       [  4.63636364,  16.42424242]])

In [127]:
correlation(a,b)

0.34613993066245985

In [128]:
np.corrcoef(a,b)

array([[ 1.        ,  0.31729494],
       [ 0.31729494,  1.        ]])